ktor:
  application:
    modules:
      - com.glion.ApplicationKt.module
  deployment:
    sslPort: 10001

  security:
    ssl:
      keyStore: ${ktor.security.ssl.keyStore}
      keyAlias: ${ktor.security.ssl.keyAlias}
      keyStorePassword: ${ktor.security.ssl.keyStorePassword}
      privateKeyPassword: ${ktor.security.ssl.privateKeyPassword}